#!/usr/bin/env python
import os
import sys
import subprocess

from methods import print_error, get_meson_file_list
from SCons.Script import *


libname = "TRXR"
projectdir = "project"

localEnv = Environment(tools=["default"], PLATFORM="")

# Build profiles can be used to decrease compile times.
# You can either specify "disabled_classes", OR
# explicitly specify "enabled_classes" which disables all other classes.
# Modify the example file as needed and uncomment the line below or
# manually specify the build_profile parameter when running SCons.

# localEnv["build_profile"] = "build_profile.json"

customs = ["custom.py"]
customs = [os.path.abspath(path) for path in customs]

opts = Variables(customs, ARGUMENTS)
opts.Add(BoolVariable('staticdeps', 'Try to build against static dependencies.', True))
opts.Add('trx_version', 'Override the TRX version string used by Meson and generated build files.', "")
opts.Add('lua_dep', 'Override the dependency() name used for Lua.', "")
opts.Update(localEnv)

staticdeps = ""
trx_version = ""

for key, value in ARGLIST:
    if key == 'staticdeps':
        staticdeps = value
    if key == 'trx_version':
        trx_version = value

if trx_version == '':
  p = subprocess.Popen("python3 ../tools/get_version", stdout=subprocess.PIPE, shell=True, cwd="../src")
  version_result, err = p.communicate()

  if p.returncode == 0:
    trx_version = version_result.strip()
  else:
    trx_version = '?'


  
trx_lua_api_sources = get_meson_file_list("trx_lua_api_sources")
trx_lua_script_sources = get_meson_file_list("trx_lua_script_sources")

cmd = f"python3 ../tools/embed_trx_lua.py --output trx_embedded_lua.c --module-root ./lua/api --modules {" ".join(trx_lua_api_sources)} --script-root ./lua --scripts {" ".join(trx_lua_script_sources)}"
subprocess.run(cmd, cwd="../src", shell=True)

cmd = f"python3 ../tools/generate_init --version {trx_version} -o ../src/trx_init.c"
subprocess.run(cmd, shell=True)

Help(opts.GenerateHelpText(localEnv))

env = localEnv.Clone()

if not (os.path.isdir("godot-cpp") and os.listdir("godot-cpp")):
    print_error("""godot-cpp is not available within this folder, as Git submodules haven't been initialized.
Run the following command to download godot-cpp:

    git submodule update --init --recursive""")
    sys.exit(1)

env = SConscript("godot-cpp/SConstruct", {"api_version": 4.7, "env": env, "customs": customs})

env.Append(CPPPATH=["src/", "../src/", "inc/", "uthash/src/"])
env.Append(CXXFLAGS="-std=c2x")
env.Append(CFLAGS=["-Dbool=_Bool", "-Dtrue=1", "-Dfalse=0", "-Dnullptr=0x0", "-Dalignas=_Alignas"])
sources = Glob("src/*.cpp") + get_meson_file_list("common_sources") + ["../src/trx_init.c", "../src/trx_embedded_lua.c"]

if env["target"] in ["editor", "template_debug"]:
    try:
        doc_data = env.GodotCPPDocData("src/gen/doc_data.gen.cpp", source=Glob("doc_classes/*.xml"))
        sources.append(doc_data)
    except AttributeError:
        print("Not including class reference as we're targeting a pre-4.3 baseline.")

# .dev doesn't inhibit compatibility, so we don't need to key it.
# .universal just means "compatible with all relevant arches" so we don't need to key it.
suffix = env['suffix'].replace(".dev", "").replace(".universal", "")

lib_filename = "{}{}{}{}".format(env.subst('$SHLIBPREFIX'), libname, suffix, env.subst('$SHLIBSUFFIX'))

library = env.SharedLibrary(
    "bin/{}/{}".format(env['platform'], lib_filename),
    source=sources,
    LIBS=["libavcodec.a", "libavfilter.a", "libavformat.a", "libavutil.a", "libswscale.a"]
)

copy = env.Install("{}/bin/{}/".format(projectdir, env["platform"]), library)

default_args = [library, copy]
Default(*default_args)
